name: urlshorty
description: URL shortening app which showcases clean architecture

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utilities
  qr_code_scanner: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/app_icon.png
  image_path_ios: assets/app_icon_ios.png

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/app_icon_ios.png
